require('./main.scss');
require('./biztrack/dashboard.scss');
require('./biztrack/modals.scss');
require('./biztrack/_closeBt4.scss');
require('./biztrack/tables.scss');
require('sweetalert/dist/sweetalert.css');
require('semantic-ui/dist/semantic.css');
require('react-widgets/lib/less/react-widgets.less');
require('react-vis/dist/main.scss');
